#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Einrichtung und Abnahme des Agenten-Containers auf dem Windows-Host (ADR 0005, Ticket #30).
# Siehe .devcontainer/README.md. Voraussetzung: Der PR ist gemergt, der Broker läuft.
#
# Aus PowerShell im Repo-Ordner:
#   & "C:\Program Files\Git\bin\bash.exe" .devcontainer/einrichten.sh
# Nur ausgewählte Stufen, z. B. nur die Abnahme:
#   $env:STUFEN = '4 5 6 7'; & "C:\Program Files\Git\bin\bash.exe" .devcontainer/einrichten.sh; Remove-Item Env:STUFEN
#
# Für einen Probelauf lassen sich PY, TOKEN_DATEI, JUST_LINK und NAME überschreiben.

TOTAL_STAGES=7
ENV_FILE="/nicht/vorhanden"   # Dieser Wizard schreibt keine .env.

PY="${PY:-/c/Program Files/Python313/python.exe}"
REPO_WURZEL="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
_toml() { "$PY" -I -c "import sys,tomllib; d=tomllib.load(open(sys.argv[1],'rb')); print(d$1)" "$REPO_WURZEL/harness.toml"; }
REPO="$(_toml "['devcontainer']['repository']")"
SLUG="$(_toml "['github_app']['slug']")"
REPO_NAME="${REPO#*/}"
OWNER="${REPO%%/*}"
IMAGE="ghcr.io/${REPO,,}/devcontainer"
NAME="${NAME:-probe}"
CONTAINER="agent-$NAME"
BRANCH="probe/devcontainer-30"
TOKEN_DATEI="${TOKEN_DATEI:-$(cygpath -u "$USERPROFILE")/.config/harness/claude-setup-token}"
JUST_LINK="${JUST_LINK:-$(cygpath -u "$LOCALAPPDATA")/Microsoft/WinGet/Links/just.exe}"
BERICHT="$(cd "$REPO_WURZEL/.." && pwd)/devcontainer-abnahme.txt"

ERGEBNISSE=()
FEHLER=0
ok()     { ERGEBNISSE+=("OK     $1"); printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
falsch() { ERGEBNISSE+=("FEHLER $1"); FEHLER=1; printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
pruefe() { if [[ "$2" == "$3" ]]; then ok "$1 ($2)"; else falsch "$1 (erwartet $3, bekommen $2)"; fi; }

# nur N: wahr, wenn Stufe N laufen soll (STUFEN leer = alle).
nur() { [[ -z "${STUFEN:-}" || " $STUFEN " == *" $1 "* ]]; }
stufe() { _STAGE_INDEX=$(($1 - 1)); stage "$2"; }

# Git Bash schreibt Argumente wie /arbeit/... sonst in Windows-Pfade um, bevor docker sie sieht.
docker() { MSYS_NO_PATHCONV=1 command docker "$@"; }
# im_container BEFEHL: als agent im Clone ausführen, Exit-Code durchreichen.
im_container() { docker exec --user agent --workdir "/arbeit/$REPO_NAME" "$CONTAINER" bash -lc "$1"; }
laeuft() { [[ "$(docker inspect --format '{{.State.Running}}' "$CONTAINER" 2>/dev/null)" == "true" ]]; }

banner "Agenten-Container einrichten und abnehmen"

# ── 1 ─────────────────────────────────────────────────────────────────────
if nur 1; then
  stufe 1 "just installieren"
  if "$JUST_LINK" --version >/dev/null 2>&1; then
    ok "just ist schon da: $("$JUST_LINK" --version)"
  else
    say "Der Wizard installiert just jetzt per winget, ohne Admin-Rechte."
    note "Fragt winget nach den Bedingungen einer Quelle: Y tippen, dann Enter."
    pause "Los mit Enter"
    winget.exe install --id Casey.Just --exact --source winget || true
    if "$JUST_LINK" --version >/dev/null 2>&1; then
      ok "just läuft: $("$JUST_LINK" --version)"
    else
      falsch "just startet nicht ($JUST_LINK). Blockt Smart App Control? Meldung an Claude schicken."
    fi
  fi
  note "PowerShell-Fenster, die schon offen sind, kennen just erst nach einem Neustart des Fensters."
  pause "Weiter mit Enter"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
if nur 2; then
  stufe 2 "Image aus GHCR holen"
  say "Der Workflow „devcontainer“ baut das Image nach dem Merge aus main."
  LAUF="$(gh run list --repo "$REPO" --workflow devcontainer --branch main --limit 1 \
    --json status,conclusion --jq '.[0] | "\(.status) \(.conclusion)"' 2>/dev/null || true)"
  say "Letzter Lauf auf main: ${LAUF:-keiner gefunden}"
  if [[ "$LAUF" != "completed success" ]]; then
    step "Im Browser den obersten Lauf öffnen und warten, bis „test“ und „veroeffentlichen“ grün sind."
    open_url "https://github.com/$REPO/actions/workflows/devcontainer.yml"
    pause "Beide Jobs grün? Enter"
  fi
  # Ohne Login holen: Nach #31 hat der Host keine GitHub-Zugangsdaten mehr.
  if DOCKER_CONFIG="$(mktemp -d)" docker pull "$IMAGE:latest"; then
    ok "Image anonym geholt: $IMAGE:latest"
  else
    warn "Anonym geht es nicht: Das Paket ist noch privat. Bitte auf öffentlich stellen."
    open_url "https://github.com/users/$OWNER/packages/container/$REPO_NAME%2Fdevcontainer/settings"
    step "Ganz unten im Abschnitt „Danger Zone“ auf „Change visibility“ klicken."
    step "„Public“ wählen, den Paketnamen „$REPO_NAME/devcontainer“ eintippen und bestätigen."
    note "Die Beschriftungen sind nicht am echten Paket geprüft. Weichen sie ab: Screenshot an Claude."
    pause "Paket öffentlich? Enter"
    if DOCKER_CONFIG="$(mktemp -d)" docker pull "$IMAGE:latest"; then
      ok "Image anonym geholt: $IMAGE:latest"
    else
      falsch "Image lässt sich nicht anonym holen"
    fi
  fi
  pause "Weiter mit Enter"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
if nur 3; then
  stufe 3 "setup-token für Claude im Container"
  say "Das setup-token ist ein eigener, einzeln widerrufbarer Claude-Zugang nur für Container."
  say "Es landet in: $TOKEN_DATEI (nur dein Benutzer darf es lesen)."
  if [[ -s "$TOKEN_DATEI" ]] && ! confirm "Es gibt schon ein setup-token. Ersetzen?"; then
    ok "setup-token vorhanden"
  else
    step "Ein NEUES PowerShell-Fenster öffnen (Windows-Taste, „PowerShell“ tippen, Enter)."
    if command -v claude >/dev/null 2>&1; then
      step "Dort eintippen:  claude setup-token"
    else
      step "Claude Code ist auf dem Host nicht installiert, deshalb aus dem Image. Dort eintippen:"
      say "    docker run --rm -it --entrypoint claude $IMAGE setup-token"
    fi
    step "Den angezeigten Link im Browser öffnen, mit deinem Claude-Konto anmelden, „Authorize“ klicken."
    step "Das Fenster zeigt danach ein Token, das mit „sk-ant-oat“ beginnt. Markieren und kopieren."
    say ""
    ask_secret SETUP_TOKEN "Token hier einfügen (Rechtsklick), es bleibt unsichtbar, dann Enter:"
    SETUP_TOKEN="${SETUP_TOKEN//[[:space:]]/}"
    if [[ "$SETUP_TOKEN" != sk-ant-oat* ]]; then
      falsch "Eingabe beginnt nicht mit sk-ant-oat (${#SETUP_TOKEN} Zeichen empfangen), nichts gespeichert"
    else
      mkdir -p "$(dirname "$TOKEN_DATEI")"
      printf '%s\n' "$SETUP_TOKEN" >"$TOKEN_DATEI"
      if MSYS_NO_PATHCONV=1 icacls "$(cygpath -w "$TOKEN_DATEI")" /inheritance:r /grant:r "${USERNAME}:F" >/dev/null; then
        ok "setup-token gespeichert (${#SETUP_TOKEN} Zeichen), nur für $USERNAME lesbar"
      else
        falsch "Rechte der Token-Datei ließen sich nicht setzen"
      fi
    fi
    unset SETUP_TOKEN
  fi
  pause "Weiter mit Enter"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
if nur 4; then
  stufe 4 "Abnahme: just agent bau $NAME"
  step "Ein NEUES PowerShell-Fenster öffnen und in den Repo-Ordner wechseln:"
  say "    cd \"$(cygpath -w "$REPO_WURZEL")\""
  step "Eintippen:  just agent bau $NAME"
  say "Erwartet: „Neuer Container $CONTAINER …“, Download, Start, dann öffnet sich Claude."
  note "Firewall und Clone brauchen beim ersten Start etwa eine halbe Minute."
  step "In Claude eintippen:  Sag kurz Hallo  und Enter. Claude muss antworten."
  step "Danach Claude mit  /exit  verlassen. Der Container läuft weiter."
  note "Fragt Claude beim Start etwas (Theme, Bestätigung): Frage merken und Claude sagen."
  pause "Claude hat geantwortet und ist mit /exit beendet? Enter"
  if laeuft; then ok "$CONTAINER läuft"; else falsch "$CONTAINER läuft nicht"; fi
  pruefe "Clone im Volume" "$(im_container 'git rev-parse --is-inside-work-tree' 2>/dev/null)" true
  pause "Weiter mit Enter"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
if nur 5; then
  stufe 5 "Abnahme: gh und Push als Bot"
  say "gh auth status im Container:"
  im_container 'gh auth status' 2>&1 | sed 's/^/      /' || true
  pruefe "gh liest das Repo mit dem App-Token" \
    "$(im_container "gh api repos/$REPO --jq .full_name" 2>/dev/null)" "$REPO"
  if im_container "git switch -q -c $BRANCH && git commit -q --allow-empty -m 'Abnahme #30: Wegwerf-Commit' && git push -q origin $BRANCH" >/dev/null 2>&1; then
    ok "Push auf $BRANCH"
  else
    falsch "Push auf $BRANCH gescheitert"
  fi
  PR_URL="$(im_container "gh pr create --base main --head $BRANCH --title 'Abnahme #30: Wegwerf-PR' --body 'Wird sofort wieder geschlossen.'" 2>/dev/null | tail -n1 || true)"
  pruefe "PR-Autor ist der Bot" \
    "$(im_container "gh pr view $BRANCH --json author --jq .author.login" 2>/dev/null)" "app/$SLUG"
  pruefe "Commit-Autor ist der Bot" "$(im_container 'git log -1 --format=%an' 2>/dev/null)" "$SLUG[bot]"
  if im_container "gh pr close $BRANCH --delete-branch" >/dev/null 2>&1; then
    ok "PR geschlossen, Branch gelöscht"
  else
    falsch "PR ließ sich nicht schließen"
  fi
  note "PR: ${PR_URL:-–}"
  pause "Weiter mit Enter"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
if nur 6; then
  stufe 6 "Negativproben"
  if im_container 'curl -sS --max-time 5 -o /dev/null https://example.com' >/dev/null 2>&1; then
    falsch "example.com ist erreichbar"
  else
    ok "example.com gesperrt"
  fi
  for programm in sudo docker; do
    if im_container "command -v $programm" >/dev/null 2>&1; then falsch "$programm vorhanden"; else ok "kein $programm"; fi
  done
  if "$PY" "$REPO_WURZEL/.devcontainer/agent.py" abmelden "$NAME"; then ok "Schlüssel abgemeldet"; else falsch "Abmelden gescheitert"; fi
  # Ein schon geholtes Token gilt bis zu 1 h weiter. Geprüft wird, dass der Broker kein neues mehr ausgibt.
  ANTWORT="$(im_container 'rm -f ~/.cache/harness/token.json; PYTHONPATH=/opt/harness/src python3 -m devcontainer.ausweis token' 2>&1 || true)"
  if [[ "$ANTWORT" == *"HTTP 403"* ]]; then
    ok "Broker gibt nach dem Abmelden kein Token mehr (403)"
  else
    falsch "Broker antwortet nach dem Abmelden: $ANTWORT"
  fi
  pause "Weiter mit Enter"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
if nur 7; then
  stufe 7 "Wegwerfen: just weg $NAME"
  step "Im PowerShell-Fenster aus Stufe 4 eintippen:  just weg $NAME"
  say "Erwartet: „$CONTAINER samt Volume entfernt“."
  pause "Erledigt? Enter"
  if docker container inspect "$CONTAINER" >/dev/null 2>&1; then falsch "Container noch da"; else ok "Container entfernt"; fi
  if docker volume inspect "$CONTAINER" >/dev/null 2>&1; then falsch "Volume noch da"; else ok "Volume entfernt"; fi
  pause "Weiter mit Enter"
fi

finish
{
  printf 'Abnahme Devcontainer, %s\n\n' "$(date '+%Y-%m-%d %H:%M')"
  for e in "${ERGEBNISSE[@]}"; do printf '%s\n' "$e"; done
  [[ -n "${PR_URL:-}" ]] && printf '\nWegwerf-PR: %s\n' "$PR_URL"
  true
} >"$BERICHT"
for e in "${ERGEBNISSE[@]}"; do note "$e"; done
if ((FEHLER)); then warn "Nicht alles grün. Bericht: $BERICHT"; else say "${GREEN}Alles grün.${RESET} Bericht: $BERICHT"; fi
