#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Einrichtung des Brokers auf dem Windows-Host (ADR 0005, Ticket #29). Siehe README.md.
#
# Aus PowerShell im Repo-Ordner:
#   & "C:\Program Files\Git\bin\bash.exe" broker/einrichten.sh [<issue-nummer-fuer-abnahme>]
# Nur ausgewählte Stufen, z. B. Stufe 3 für ein Update nach einem Merge:
#   $env:STUFEN = '3'; & "C:\Program Files\Git\bin\bash.exe" broker/einrichten.sh; Remove-Item Env:STUFEN
#
# Für einen Probelauf lassen sich ZIEL, DATEN und PY überschreiben.

TOTAL_STAGES=10

KONTO="harness-broker"
ZIEL_WIN='C:\Program Files\harness-broker'
DATEN_WIN='C:\ProgramData\harness-broker'
ZIEL="${ZIEL:-/c/Program Files/harness-broker}"
DATEN="${DATEN:-/c/ProgramData/harness-broker}"
PY="${PY:-/c/Program Files/Python313/python.exe}"
DIENST="$ZIEL/quelle/broker/dienst.py"

REPO_WURZEL="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
REPO="$(git -C "$REPO_WURZEL" remote get-url origin | sed -E 's#^(https://github.com/|git@github.com:)##; s#\.git$##')"
_toml() { "$PY" -I -c "import sys,tomllib; d=tomllib.load(open(sys.argv[1],'rb')); print(d$1)" "$REPO_WURZEL/harness.toml"; }
SLUG="$(_toml "['github_app']['slug']")"
BOT_ID="$(_toml "['github_app']['bot_user_id']")"
PORT="$(_toml "['broker']['port']")"
ISSUE="${1:-}"
BERICHT="$(cd "$REPO_WURZEL/.." && pwd)/broker-abnahme.txt"
ARBEIT="$(mktemp -d)"
trap 'rm -rf "$ARBEIT"' EXIT

ERGEBNISSE=()
FEHLER=0
ok()     { ERGEBNISSE+=("OK     $1"); printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
falsch() { ERGEBNISSE+=("FEHLER $1"); FEHLER=1; printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
pruefe() { if [[ "$2" == "$3" ]]; then ok "$1 ($2)"; else falsch "$1 (erwartet $3, bekommen $2)"; fi; }

# nur N: wahr, wenn Stufe N laufen soll (STUFEN leer = alle).
nur() { [[ -z "${STUFEN:-}" || " $STUFEN " == *" $1 "* ]]; }
stufe() { _STAGE_INDEX=$(($1 - 1)); stage "$2"; }

# admin_block: PowerShell-Befehle von stdin in die Zwischenablage legen und anzeigen.
admin_block() {
  local block; block="$(cat)"
  printf '%s\r\n' "$block" | clip.exe
  step "Der Befehl liegt in der Zwischenablage. Ins Fenster „Administrator: Windows PowerShell“"
  say  "  klicken, Strg+V drücken, dann Enter. Warten, bis „FERTIG Stufe …“ erscheint."
  note "Bei roter Fehlermeldung: hier Strg+C und den roten Text an Claude schicken."
  printf '\n%s' "$DIM"; printf '%s\n' "$block" | sed 's/^/      /'; printf '%s\n' "$RESET"
}

# broker PFAD JSON BEARER: Anfrage an den Broker. Statuscode nach stdout, Körper nach $ARBEIT/antwort.
broker() {
  curl -s -o "$ARBEIT/antwort" -w '%{http_code}' -X POST -H "Authorization: Bearer $3" \
    -H 'Content-Type: application/json' -d "$2" "http://127.0.0.1:$PORT$1" 2>/dev/null || true
}
# github METHODE PFAD TOKEN [JSON]: Anfrage an die GitHub-API. Statuscode nach stdout, Körper nach $ARBEIT/gh.
github() {
  local daten=()
  [[ -n "${4:-}" ]] && daten=(-d "$4")
  curl -s -o "$ARBEIT/gh" -w '%{http_code}' -X "$1" -H "Authorization: Bearer $3" \
    -H 'Accept: application/vnd.github+json' "${daten[@]}" "https://api.github.com$2" 2>/dev/null || true
}
json() { "$PY" -I -c "import json,sys; print(json.load(open(sys.argv[1]))$1)" "$2" 2>/dev/null || true; }
admin_geheimnis() { cat "$DATEN/admin-geheimnis" 2>/dev/null || true; }
neuer_schluessel() { "$PY" -I -c "import secrets; print(secrets.token_urlsafe(24))"; }
anmelden() {
  broker /schluessel "{\"schluessel\": \"$1\", \"rolle\": \"$2\", \"ablauf\": $(($(date +%s) + 900))}" "$(admin_geheimnis)"
}
abmelden() { broker /schluessel/abmelden "{\"schluessel\": \"$1\"}" "$(admin_geheimnis)"; }
lauscht() { netstat -ano 2>/dev/null | grep -qE "127\.0\.0\.1:$PORT +[^ ]+ +LISTENING"; }

# git_mit_token TOKEN ARGS...: git ohne die Zugangsdaten des Owners, nur mit dem Rollen-Token.
git_mit_token() {
  local token="$1" basic
  shift
  basic="$(printf 'x-access-token:%s' "$token" | base64 -w0)"
  GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
    -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $basic" "$@"
}

banner "Broker für Rollen-Tokens einrichten"

# ── 1 ─────────────────────────────────────────────────────────────────────
if nur 1; then
  stufe 1 "Admin-Fenster öffnen"
  say "Alle Admin-Schritte laufen in EINEM PowerShell-Fenster mit Admin-Rechten, ohne Profil."
  step "Windows-Taste + R drücken. Es öffnet sich „Ausführen“."
  step "Eintippen:  powershell -NoProfile"
  step "Strg + Umschalt + Enter drücken (nicht nur Enter)."
  step "Benutzerkontensteuerung „Möchten Sie zulassen …“ → Ja."
  say "Das Fenster heißt jetzt „Administrator: Windows PowerShell“. Offen lassen bis zum Schluss."
  pause "Fenster offen? Enter"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
if nur 2; then
  stufe 2 "Dienstkonto $KONTO anlegen"
  step "In Bitwarden: Neu → Login, Name „$KONTO (Windows-Dienstkonto)“, Benutzername „$KONTO“."
  step "Beim Passwort auf „Passwort generieren“ (Würfel-Symbol), Länge 32. Speichern."
  step "Passwort kopieren (Kopier-Symbol neben dem Passwort)."
  pause "Passwort in Bitwarden gespeichert und kopiert? Enter"
  admin_block <<'PS'
& { $ErrorActionPreference = 'Stop'; $konto = 'harness-broker'
$global:cred = Get-Credential -UserName "$env:COMPUTERNAME\$konto" -Message 'Passwort des Dienstkontos aus Bitwarden einfuegen'
if (-not (Get-LocalUser -Name $konto -ErrorAction SilentlyContinue)) { New-LocalUser -Name $konto -Password $global:cred.Password -PasswordNeverExpires -UserMayNotChangePassword -AccountNeverExpires -Description 'Broker fuer Rollen-Tokens (ADR 0005)' | Out-Null }
if (-not (Get-LocalGroupMember -SID 'S-1-5-32-545' -Member $konto -ErrorAction SilentlyContinue)) { Add-LocalGroupMember -SID 'S-1-5-32-545' -Member $konto }
$k = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList'
if (-not (Test-Path $k)) { New-Item -Path $k -Force | Out-Null }
New-ItemProperty -Path $k -Name $konto -Value 0 -PropertyType DWord -Force | Out-Null
Get-LocalUser $konto | Format-List Name, Enabled, PasswordExpires
'FERTIG Stufe 2' }
PS
  note "Es öffnet sich der Dialog „Anmeldeinformationen“. Der Benutzername steht schon drin."
  note "Ins Feld Kennwort das Passwort aus Bitwarden einfügen (Strg+V), dann OK."
  note "Erwartet: Name $KONTO, Enabled True, PasswordExpires leer."
  pause "„FERTIG Stufe 2“ erschienen? Enter"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
if nur 3; then
  stufe 3 "Broker-Code aus main installieren"
  say "Holt $REPO (Branch main) direkt von GitHub nach $ZIEL_WIN"
  say "und installiert die Pakete mit festen Prüfsummen. Dauert etwa eine Minute."
  sed "s#__REPO__#$REPO#g" <<'PS' | admin_block
& { $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'
$ziel = 'C:\Program Files\harness-broker'; $py = 'C:\Program Files\Python313\python.exe'
New-Item -ItemType Directory -Force $ziel | Out-Null; $zip = Join-Path $ziel 'main.zip'
Invoke-WebRequest -UseBasicParsing 'https://github.com/__REPO__/archive/refs/heads/main.zip' -OutFile $zip
foreach ($d in "$ziel\quelle", "$ziel\entpackt") { if (Test-Path $d) { Remove-Item -Recurse -Force $d } }
Expand-Archive $zip -DestinationPath "$ziel\entpackt"
Move-Item (Get-ChildItem "$ziel\entpackt" | Select-Object -First 1).FullName "$ziel\quelle"; Remove-Item -Recurse -Force "$ziel\entpackt", $zip
& $py -I -m pip install --isolated --no-cache-dir --require-hashes --only-binary=:all: --target "$ziel\quelle\broker\lib" -r "$ziel\quelle\broker\requirements.txt"; if ($LASTEXITCODE) { throw 'pip fehlgeschlagen' }
icacls "$ziel\quelle" /reset /T /C /Q; if ($LASTEXITCODE) { throw 'icacls fehlgeschlagen' }
& $py -E -s "$ziel\quelle\broker\dienst.py" --help; if ($LASTEXITCODE) { throw 'Broker startet nicht' }
'FERTIG Stufe 3' }
PS
  note "Erwartet: „Successfully installed …“, dann die Hilfe „usage: broker …“."
  note "pip legt die Pakete über deinen TEMP-Ordner an; icacls /reset gibt ihnen die Rechte von Program Files."
  pause "„FERTIG Stufe 3“ erschienen? Enter"
  if (: >"$ZIEL/quelle/broker/lib/.schreibprobe") 2>/dev/null; then
    rm -f "$ZIEL/quelle/broker/lib/.schreibprobe"
    falsch "Dein User kann in $ZIEL_WIN schreiben"
  else
    ok "Dein User kann in $ZIEL_WIN nicht schreiben"
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
if nur 4; then
  stufe 4 "Datenordner mit Rechten anlegen"
  say "In $DATEN_WIN liegen Key, Admin-Geheimnis und Log."
  say "Das Dienstkonto darf dort schreiben, du nur lesen, sonst niemand außer Admins."
  admin_block <<'PS'
& { $ErrorActionPreference = 'Stop'; $daten = 'C:\ProgramData\harness-broker'; $ich = "$env:USERDOMAIN\$env:USERNAME"
New-Item -ItemType Directory -Force $daten | Out-Null
icacls $daten /inheritance:r /grant:r '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-544:(OI)(CI)F' 'harness-broker:(OI)(CI)M' "${ich}:(OI)(CI)RX"; if ($LASTEXITCODE) { throw 'icacls fehlgeschlagen' }
icacls $daten
'FERTIG Stufe 4' }
PS
  note "Erwartet: genau vier Einträge: NT AUTHORITY\\SYSTEM (F), BUILTIN\\Administrators (F),"
  note "…\\$KONTO (M) und dein Benutzer (RX)."
  pause "„FERTIG Stufe 4“ erschienen? Enter"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
if nur 5; then
  stufe 5 "Private Key als Dienstkonto importieren"
  say "Du fügst den Key im Admin-Fenster ein. Es reicht ihn an das Dienstkonto weiter, das ihn"
  say "verschlüsselt. Nur dieses Konto kann ihn danach öffnen."
  admin_block <<'PS'
& { $ErrorActionPreference = 'Stop'
$daten = 'C:\ProgramData\harness-broker'; $ziel = 'C:\Program Files\harness-broker'; $imp = "$daten\import"
if (-not $global:cred) { $global:cred = Get-Credential -UserName "$env:COMPUTERNAME\harness-broker" -Message 'Passwort des Dienstkontos aus Bitwarden einfuegen' }
New-Item -ItemType Directory -Force $imp | Out-Null
icacls $imp /inheritance:r /grant:r '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-544:(OI)(CI)F' 'harness-broker:(OI)(CI)M' | Out-Null; if ($LASTEXITCODE) { throw 'icacls fehlgeschlagen' }
Write-Host 'Jetzt den Private Key aus Bitwarden hier einfuegen (Rechtsklick ins Fenster).' -ForegroundColor Yellow
$zeilen = @(); do { $z = Read-Host; $zeilen += $z.Trim() } until ($z -match '-----END [A-Z ]*PRIVATE KEY-----')
Clear-Host
"Gelesen: $($zeilen.Count) Zeilen, erste: $($zeilen[0]), letzte: $($zeilen[-1])"
Set-Content -Path "$imp\key.pem" -Value ($zeilen -join "`n") -Encoding Ascii
$py = 'C:\Program Files\Python313\python.exe'; $dienst = "`"$ziel\quelle\broker\dienst.py`""
try {
Start-Process -FilePath $py -ArgumentList '-E', '-s', $dienst, 'key-import', '--daten', "`"$daten`"" -Credential $global:cred -LoadUserProfile -WorkingDirectory $ziel -RedirectStandardInput "$imp\key.pem" -RedirectStandardOutput "$imp\ausgabe.txt" -RedirectStandardError "$imp\fehler.txt" -Wait
} finally { Remove-Item "$imp\key.pem" -Force }
Get-Content "$imp\ausgabe.txt"
Start-Process -FilePath $py -ArgumentList '-E', '-s', $dienst, 'key-pruefen', '--daten', "`"$daten`"" -Credential $global:cred -LoadUserProfile -WorkingDirectory $ziel -RedirectStandardOutput "$imp\ausgabe.txt" -RedirectStandardError "$imp\fehler.txt" -Wait
Get-Content "$imp\ausgabe.txt", "$imp\fehler.txt"
'FERTIG Stufe 5' }
PS
  step "Im Admin-Fenster erscheint gelb „Jetzt den Private Key aus Bitwarden hier einfuegen“."
  step "In Bitwarden den Private Key der App kopieren (von -----BEGIN bis -----END … KEY-----)."
  step "Rechtsklick ins Admin-Fenster. Der Rest läuft von selbst, danach wird das Fenster geleert."
  note "Kommt nach dem Rechtsklick nichts, fehlte am Ende ein Zeilenumbruch: einmal Enter drücken."
  say "Erwartet: „Gelesen: … Zeilen …“, „Key importiert …“, „Fingerabdruck SHA256:…“, „Key lesbar“."
  open_url "https://github.com/settings/apps/$SLUG"
  step "Auf der App-Seite ganz unten unter „Private keys“: Der Fingerabdruck dort muss gleich sein."
  warn "Der Key war in der Zwischenablage. Falls der Verlauf an ist: Windows-Taste + V → „Alle löschen“."
  pause "Fingerabdruck gleich und „Key lesbar“? Enter"
  printf '' | clip.exe
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
if nur 6; then
  stufe 6 "Autostart einrichten und Broker starten"
  say "Eine Aufgabe „$KONTO“ startet den Broker beim Systemstart unter dem Dienstkonto. Dafür braucht"
  say "das Konto das Windows-Recht „Anmelden als Batchauftrag“; der Block setzt es, falls es fehlt."
  admin_block <<'PS'
& { $ErrorActionPreference = 'Stop'; $ziel = 'C:\Program Files\harness-broker'; $daten = 'C:\ProgramData\harness-broker'; $imp = "$daten\import"
$sid = (Get-LocalUser -Name 'harness-broker').SID.Value
secedit /export /cfg "$imp\rechte-alt.inf" /areas USER_RIGHTS /quiet; if ($LASTEXITCODE) { throw 'secedit export fehlgeschlagen' }
$alt = Get-Content "$imp\rechte-alt.inf" | Where-Object { $_ -match '^SeBatchLogonRight\s*=' }
if ($alt -match [regex]::Escape("*$sid")) { 'Recht ist schon da' } else {
$wert = if ($alt) { ($alt -split '=', 2)[1].Trim() + ",*$sid" } else { "*$sid" }
@('[Unicode]', 'Unicode=yes', '[Version]', 'signature="$CHICAGO$"', 'Revision=1', '[Privilege Rights]', "SeBatchLogonRight = $wert") | Set-Content "$imp\rechte-neu.inf" -Encoding Unicode
secedit /configure /db "$imp\rechte.sdb" /cfg "$imp\rechte-neu.inf" /areas USER_RIGHTS /quiet; if ($LASTEXITCODE) { throw 'secedit configure fehlgeschlagen' }
'Recht Anmelden als Batchauftrag fuer harness-broker gesetzt' }
Remove-Item "$imp\rechte-*.inf", "$imp\rechte.sdb" -Force -ErrorAction SilentlyContinue
if (-not $global:cred) { $global:cred = Get-Credential -UserName "$env:COMPUTERNAME\harness-broker" -Message 'Passwort des Dienstkontos aus Bitwarden einfuegen' }
$aktion = New-ScheduledTaskAction -Execute 'C:\Program Files\Python313\python.exe' -Argument "-E -s `"$ziel\quelle\broker\dienst.py`" start --daten `"$daten`" --konfig `"$ziel\quelle\harness.toml`"" -WorkingDirectory $ziel
$einst = New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
Register-ScheduledTask -TaskName 'harness-broker' -Action $aktion -Trigger (New-ScheduledTaskTrigger -AtStartup) -Settings $einst -User $global:cred.UserName -Password $global:cred.GetNetworkCredential().Password -RunLevel Limited -Force | Out-Null
Start-ScheduledTask -TaskName 'harness-broker'; Start-Sleep -Seconds 8
Get-ScheduledTaskInfo -TaskName 'harness-broker' | Format-List LastRunTime, LastTaskResult
'FERTIG Stufe 6' }
PS
  note "Erwartet: „Recht … gesetzt“ oder „Recht ist schon da“, dann LastTaskResult 267009 (heißt: läuft)."
  note "267011 heißt: nie gestartet. Dann hier Strg+C und die Ausgabe an Claude schicken."
  pause "„FERTIG Stufe 6“ erschienen? Enter"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
if nur 7; then
  stufe 7 "Abnahme: Broker läuft, Key ist für dich nicht lesbar"
  for _ in 1 2 3 4 5 6 7 8 9 10; do lauscht && break; sleep 1; done
  if lauscht; then ok "Broker lauscht auf 127.0.0.1:$PORT"; else falsch "Broker lauscht nicht auf 127.0.0.1:$PORT"; fi
  if [[ -n "$(admin_geheimnis)" ]]; then ok "Admin-Geheimnis für dich lesbar"; else falsch "Admin-Geheimnis fehlt oder nicht lesbar"; fi
  ausgabe="$("$PY" -E -s "$DIENST" key-pruefen --daten "$DATEN" 2>&1 || true)"
  note "$ausgabe"
  if [[ "$ausgabe" == *"NICHT lesbar"* ]]; then ok "Key unter deinem User nicht lesbar"; else falsch "Key unter deinem User lesbar oder Prüfung kaputt"; fi
  pause "Weiter mit Enter"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
if nur 8; then
  stufe 8 "Abnahme: Rechte der Rollen bei GitHub"
  [[ -n "$ISSUE" ]] || ask ISSUE "Nummer des Tickets, das den Abnahme-Kommentar bekommt (z. B. 29):"
  say "Der Wizard holt je ein Token der Rollen planung und bau und probiert sie an GitHub aus."
  git -c credential.helper= clone -q --depth 1 "https://github.com/$REPO.git" "$ARBEIT/klon" 2>/dev/null || true
  git -C "$ARBEIT/klon" -c user.name="$SLUG[bot]" -c user.email="$BOT_ID+$SLUG[bot]@users.noreply.github.com" \
    commit -q --allow-empty -m "Abnahme Broker: Wegwerf-Commit" || true

  SP="$(neuer_schluessel)"
  SB="$(neuer_schluessel)"
  pruefe "Schlüssel der Rolle planung angemeldet" "$(anmelden "$SP" planung)" 204
  pruefe "Token für planung geholt" "$(broker /token '{"rolle": "planung"}' "$SP")" 200
  TP="$(json "['token']" "$ARBEIT/antwort")"
  pruefe "planung kommentiert #$ISSUE" "$(github POST "/repos/$REPO/issues/$ISSUE/comments" "$TP" \
    '{"body": "Abnahme Broker: Kommentar mit einem Token der Rolle *Planung*."}')" 201
  KOMMENTAR="$(json "['html_url']" "$ARBEIT/gh")"
  if git_mit_token "$TP" -C "$ARBEIT/klon" push -q origin HEAD:refs/heads/abnahme/broker-planung 2>"$ARBEIT/push"; then
    falsch "planung konnte pushen"
  else
    ok "planung kann nicht pushen: $(grep -m1 -iE 'denied|403|not allowed|error' "$ARBEIT/push" || true)"
  fi

  pruefe "Schlüssel der Rolle bau angemeldet" "$(anmelden "$SB" bau)" 204
  pruefe "Token für bau geholt" "$(broker /token '{"rolle": "bau"}' "$SB")" 200
  TB="$(json "['token']" "$ARBEIT/antwort")"
  if git_mit_token "$TB" -C "$ARBEIT/klon" push -q origin HEAD:refs/heads/abnahme/broker-bau 2>"$ARBEIT/push"; then
    ok "bau pusht Branch abnahme/broker-bau"
  else
    falsch "bau konnte nicht pushen: $(tr '\n' ' ' <"$ARBEIT/push")"
  fi
  pruefe "bau öffnet einen PR" "$(github POST "/repos/$REPO/pulls" "$TB" \
    '{"title": "Abnahme Broker: Wegwerf-PR", "head": "abnahme/broker-bau", "base": "main", "body": "Wird sofort wieder geschlossen."}')" 201
  PR="$(json "['number']" "$ARBEIT/gh")"
  PR_URL="$(json "['html_url']" "$ARBEIT/gh")"
  pruefe "PR-Autor ist der Bot" "$(json "['user']['login']" "$ARBEIT/gh")" "$SLUG[bot]"
  if [[ -n "$PR" ]]; then
    pruefe "bau schließt den PR wieder" "$(github PATCH "/repos/$REPO/pulls/$PR" "$TB" '{"state": "closed"}')" 200
  fi
  pruefe "bau löscht den Wegwerf-Branch" "$(github DELETE "/repos/$REPO/git/refs/heads/abnahme/broker-bau" "$TB")" 204
  abmelden "$SP" >/dev/null
  abmelden "$SB" >/dev/null
  note "Kommentar: ${KOMMENTAR:-–}"
  note "PR:        ${PR_URL:-–}"
  pause "Weiter mit Enter"
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
if nur 9; then
  stufe 9 "Negativprobe: Broker lehnt ab"
  SX="$(neuer_schluessel)"
  pruefe "unbekannter Schlüssel" "$(broker /token '{"rolle": "bau"}' "$SX")" 403
  anmelden "$SX" planung >/dev/null
  pruefe "fremde Rolle (planung will bau)" "$(broker /token '{"rolle": "bau"}' "$SX")" 403
  abmelden "$SX" >/dev/null
  pruefe "abgemeldeter Schlüssel" "$(broker /token '{"rolle": "planung"}' "$SX")" 403
  pruefe "Anmelden ohne Admin-Geheimnis" \
    "$(broker /schluessel "{\"schluessel\": \"$SX\", \"rolle\": \"bau\", \"ablauf\": 9999999999}" geraten)" 403
  pause "Weiter mit Enter"
fi

# ── 10 ────────────────────────────────────────────────────────────────────
if nur 10; then
  stufe 10 "Kill-Switch: Broker stoppen und wieder starten"
  SK="$(neuer_schluessel)"
  anmelden "$SK" planung >/dev/null
  ALT="$(admin_geheimnis)"
  admin_block <<'PS'
Stop-ScheduledTask -TaskName 'harness-broker'; 'FERTIG Stufe 10a'
PS
  pause "„FERTIG Stufe 10a“ erschienen? Enter"
  sleep 2
  if lauscht; then falsch "Broker läuft nach dem Stoppen weiter"; else ok "Broker nach dem Stoppen weg"; fi
  pruefe "Token-Anfrage bei gestopptem Broker (keine Verbindung)" "$(broker /token '{"rolle": "planung"}' "$SK")" 000
  admin_block <<'PS'
Start-ScheduledTask -TaskName 'harness-broker'; 'FERTIG Stufe 10b'
PS
  pause "„FERTIG Stufe 10b“ erschienen? Enter"
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    lauscht && [[ "$(admin_geheimnis)" != "$ALT" ]] && break
    sleep 1
  done
  if lauscht; then ok "Broker läuft wieder"; else falsch "Broker startet nicht wieder"; fi
  pruefe "alte Anmeldung nach Neustart ungültig" "$(broker /token '{"rolle": "planung"}' "$SK")" 403
  say "Das Admin-Fenster kannst du jetzt schließen (exit)."
  pause "Weiter mit Enter"
fi

finish
{
  printf 'Abnahme Broker, %s\n\n' "$(date '+%Y-%m-%d %H:%M')"
  for e in "${ERGEBNISSE[@]}"; do printf '%s\n' "$e"; done
  [[ -n "${KOMMENTAR:-}" ]] && printf '\nKommentar: %s\n' "$KOMMENTAR"
  [[ -n "${PR_URL:-}" ]] && printf 'Wegwerf-PR: %s\n' "$PR_URL"
  true
} >"$BERICHT"
for e in "${ERGEBNISSE[@]}"; do note "$e"; done
if ((FEHLER)); then warn "Nicht alles grün. Bericht: $BERICHT"; else say "${GREEN}Alles grün.${RESET} Bericht: $BERICHT"; fi
